lib/task_tracker2_web/router.ex
defmodule TaskTracker2Web.Router do
  use TaskTracker2Web, :router

  alias TaskTracker2Web.SessionPlugs
  import TaskTracker2Web.SessionPlugs, only: [get_current_user: 2]

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:get_current_user)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/", TaskTracker2Web do
    # Use the default browser stack
    pipe_through(:browser)

    get("/", PageController, :index)
    get("/feed", PageController, :feed)
    get("/manage", PageController, :manage)

    resources("/users", UserController)
    resources("/tasks", TaskController)
    post("/create_with_login", TaskController, :create_with_login)
    resources("/managements", ManagementController)

    post("/session", SessionController, :create)
    delete("/session", SessionController, :delete)
  end

  scope "/api/v1", TaskTracker2Web do
    pipe_through(:api)
    resources("/time_blocks", TimeBlockController, except: [:new, :edit])
  end

  # Other scopes may use custom stacks.
  # scope "/api", TaskTracker2Web do
  #   pipe_through :api
  # end
end

lib/task_tracker2_web/templates/page/index.html.eex
<h1>Log In</h1>
<!-- session_path(@conn, :create) -->
<%= form_tag("/session", method: :post) do %>
  <div class="form-group">
    Email
    <input type="email" name="email" placeholder="user@example.com" >
  </div>
  <!-- passwords come later -->
  <div class="form-group">
    <button class="btn btn-primary">Log in</button>
    <%= link "Register", to: user_path(@conn, :new) %>
  </div>
<% end %>

lib/task_tracker2_web/templates/page/task.html.eex
<%= if @current_user do %>
  <script>
   window.current_user_id = "<%= @current_user.id %>";
   window.time_path = "<%= time_block_path(@conn, :index) %>";
  </script>

  <div class="row">
    <div class="col">
      <%= form_tag("/create_with_login", method: :post) do %>
        <div class="form-group">
          <label class="control-label" for="task_to_id">To</label>
          <input class="form-control" id="task_to_id" name="to_id" type="text">
        </div>

        <div class="form-group">
          <label class="control-label" for="task_title">Title</label>
          <input class="form-control" id="task_title" name="title" type="text">
        </div>

        <div class="form-group">
          <label class="control-label" for="task_body">Body</label>
          <textarea class="form-control" id="task_body" name="body"></textarea>
        </div>

        <div class="form-group">
          <%= submit "Submit", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>

  <h1>User Info</h1>
  <p>name: <%= @current_user.name %></p>
  <p>email: <%= @current_user.email %></p>
  <p>user id: <%= @current_user.id %></p>

  <h2>User's manager</h2>
  <%= Enum.map @managers, fn manager -> %>
    <div class="row">
      <div class="col">
        <p>manager's name: <%= manager.manager.name %></p>
        <p>manager's email: <%= manager.manager.email %></p>
        <p>manager's id: <%= manager.manager.id %></p>
        <hr />
      </div>
    </div>
  <% end %>

  <h2>You Manage</h2>
  <%= Enum.map @manageds, fn p -> %>
    <div class="row">
      <div class="col">
        <p>name: <%= p.managed.name %></p>
        <p>email: <%= p.managed.email %></p>
        <p>id: <%= p.managed.id %></p>
        <hr />
      </div>
    </div>
  <% end %>

  <h1>Your Tasks</h1>
  <%= Enum.map @tasks_your, fn post -> %>
    <div class="row">
      <div class="col">
        <div class="card">
          <div class="card-body">
            <h6 class="card-title"><%= post.user_from.name %> gave you this work</h6>
            <p class = "text-info"><%= post.title %></p>
            <p><%= post.body %></p>
            <p><strong><%=
            if post.finished do
              "Finished"
            else
              "Not finished"
            end %></strong></p>
            <div id="<%= "div-blocks-task-" <> Integer.to_string(post.id) %>">
              <%= Enum.map post.time_block, fn t -> %>
                <div
                  class="div-time-block"
                  data-div-id= "<%= "div" <> Integer.to_string(t.id) %>">
                  <span>start time: </span>
                  <input
                    type="date" value="<%= NaiveDateTime.to_date(t.start) %>"
                    id="<%= "input-start-date-" <> Integer.to_string(t.id) %>">
                  <input
                    type="time"
                    id="<%= "input-start-time-" <> Integer.to_string(t.id) %>"
                    value="<%= NaiveDateTime.truncate(t.start,:second)|>NaiveDateTime.to_time() %>">
                  <br>
                  <span>end time:&nbsp;</span>
                  <input
                    type="date" value="<%= NaiveDateTime.to_date(t.end) %>"
                    id="<%= "input-end-date-" <> Integer.to_string(t.id) %>">
                  <input
                    type="time"
                    id="<%= "input-end-time-" <> Integer.to_string(t.id) %>"
                    value="<%= NaiveDateTime.truncate(t.end,:second)|>NaiveDateTime.to_time() %>">
                  <br>
                  <button
                    class="delete-button btn btn-danger"
                    data-delete-id="<%= t.id %>">Delete</button>
                  <button
                    class="update-button btn primary"
                    data-task-id = "<%= post.id %>"
                    data-update-id="<%= t.id %>">Update</button>
                </div>
                <br>
              <% end %>
            </div>
            <button class="start-button btn btn-secondary"
                    data-task-id = "<%= post.id %>"
                    data-start-item="">
              Start
            </button>
            <br /><br />
            <%= link "Edit", to: task_path(@conn, :edit, post.id) %>
          </div>
        </div>
      </div>
    </div>
  <% end %>

  <h1>The tasks you assign to others</h1>
    <%= Enum.map @tasks_your, fn post -> %>
    <div class="row">
      <div class="col">
        <div class="card">
          <div class="card-body">
            <h6 class="card-title">You gave this work to <%= post.user_from.name %></h6>
            <p class = "text-info"><%= post.title %></p>
            <p><%= post.body %></p>
            <p><strong><%=
            if post.finished do
              "Finished"
            else
              "Not finished"
            end %></strong></p>
            <%= link "Edit", to: task_path(@conn, :edit, post.id) %>
            <br />
            <%= Enum.map post.time_block, fn t -> %>
              <span>start time: </span>
              <%= NaiveDateTime.to_date(t.start) %>
              <%= NaiveDateTime.truncate(t.start,:second)|>NaiveDateTime.to_time() %>
              <br>
              <span>end time:&nbsp;</span>
              <%= NaiveDateTime.to_date(t.end) %>
              <%= NaiveDateTime.truncate(t.end,:second)|>NaiveDateTime.to_time() %>
              <br>
              <hr>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>